spring:
  application:
    name: guyi-api-main
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guyi_api2
    username: root
    password: zsh654321
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    # 如果没有使用 redis, 将其改为 none
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 1
server:
  port: 7529
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost  # 设置种 cookie 的范围
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# 这段配置仅供测试，实际应该从数据库中取对应的 ak / sk
guyiapi:
  client:
    access-key: guyi
    secret-key: 12345678
dubbo:
  # 将当前项目设置为服务提供者
  application:
    name: dubbo-springboot-demo-provider
  # 设置协议，这里使用 dubbo
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848